apiVersion: v1
kind: Service
metadata:
  name: precis-api
  namespace: precis
spec:
  selector:
    app: precis-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
