"""table highlights

Revision ID: 348221d56fed
Revises: f1b0d3e80c1c
Create Date: 2026-04-26 12:26:30.598669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '348221d56fed'
down_revision: Union[str, None] = 'f1b0d3e80c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_highlights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('rows', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('columns', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['document_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_highlights_document_id'), 'table_highlights', ['document_id'], unique=False)
    op.create_index(op.f('ix_table_highlights_node_id'), 'table_highlights', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_highlights_node_id'), table_name='table_highlights')
    op.drop_index(op.f('ix_table_highlights_document_id'), table_name='table_highlights')
    op.drop_table('table_highlights')
    # ### end Alembic commands ###
