"""add_document_content_tree_tables

Revision ID: 57ab85b20a72
Revises: 9cc38bc3a4ba
Create Date: 2026-04-25 22:28:49.711654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57ab85b20a72'
down_revision: Union[str, None] = '9cc38bc3a4ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('heading', 'paragraph', 'list_item', 'table', 'image', 'code', name='nodetype'), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['document_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'seq')
    )
    op.create_index(op.f('ix_document_nodes_document_id'), 'document_nodes', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_nodes_parent_id'), 'document_nodes', ['parent_id'], unique=False)
    op.drop_column('documents', 'document_content_tree')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_content_tree', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_document_nodes_parent_id'), table_name='document_nodes')
    op.drop_index(op.f('ix_document_nodes_document_id'), table_name='document_nodes')
    op.drop_table('document_nodes')
    # ### end Alembic commands ###
