"""image highlights

Revision ID: 69ca3547afcf
Revises: 348221d56fed
Create Date: 2026-04-26 12:38:59.119808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ca3547afcf'
down_revision: Union[str, None] = '348221d56fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_highlights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['document_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_highlights_document_id'), 'image_highlights', ['document_id'], unique=False)
    op.create_index(op.f('ix_image_highlights_node_id'), 'image_highlights', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_highlights_node_id'), table_name='image_highlights')
    op.drop_index(op.f('ix_image_highlights_document_id'), table_name='image_highlights')
    op.drop_table('image_highlights')
    # ### end Alembic commands ###
