"""polymorphic node content

Revision ID: e9c32d53cea3
Revises: 57ab85b20a72
Create Date: 2026-04-26 03:23:48.486377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9c32d53cea3'
down_revision: Union[str, None] = '57ab85b20a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Destructive: wipe existing nodes/highlights and rebuild the nodetype
    # enum with the reduced value set (text, table, image).
    op.execute('TRUNCATE TABLE document_nodes, highlights RESTART IDENTITY CASCADE')
    op.execute('ALTER TABLE document_nodes ALTER COLUMN type TYPE varchar USING type::text')
    op.execute('DROP TYPE nodetype')
    op.execute("CREATE TYPE nodetype AS ENUM ('text', 'table', 'image')")
    op.execute('ALTER TABLE document_nodes ALTER COLUMN type TYPE nodetype USING type::nodetype')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_contents',
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('alt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['document_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('table_contents',
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('rows', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['document_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('text_contents',
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['document_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.drop_column('document_nodes', 'page')
    op.drop_column('document_nodes', 'content')
    op.drop_column('document_nodes', 'text')
    op.drop_column('document_nodes', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_nodes', sa.Column('level', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('document_nodes', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('document_nodes', sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('document_nodes', sa.Column('page', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('text_contents')
    op.drop_table('table_contents')
    op.drop_table('image_contents')
    # ### end Alembic commands ###

    op.execute('ALTER TABLE document_nodes ALTER COLUMN type TYPE varchar USING type::text')
    op.execute('DROP TYPE nodetype')
    op.execute("CREATE TYPE nodetype AS ENUM ('heading', 'paragraph', 'list_item', 'table', 'image', 'code')")
    op.execute('ALTER TABLE document_nodes ALTER COLUMN type TYPE nodetype USING type::nodetype')
