"""per content type highlights text variant

Revision ID: f1b0d3e80c1c
Revises: e9c32d53cea3
Create Date: 2026-04-26 12:12:15.241934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1b0d3e80c1c'
down_revision: Union[str, None] = 'e9c32d53cea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_highlights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['document_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_highlights_document_id'), 'text_highlights', ['document_id'], unique=False)
    op.create_index(op.f('ix_text_highlights_node_id'), 'text_highlights', ['node_id'], unique=False)
    op.drop_index('ix_highlights_document_id', table_name='highlights')
    op.drop_table('highlights')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlights',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_offset', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_offset', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name='highlights_document_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='highlights_pkey')
    )
    op.create_index('ix_highlights_document_id', 'highlights', ['document_id'], unique=False)
    op.drop_index(op.f('ix_text_highlights_node_id'), table_name='text_highlights')
    op.drop_index(op.f('ix_text_highlights_document_id'), table_name='text_highlights')
    op.drop_table('text_highlights')
    # ### end Alembic commands ###
